### ISSUE TITLE
Responsive Size & Normalize.

### ISSUE THREAD

**Issue by IanCiarulli** [FranFara/Challenge#3]
https://github.com/FranFara/Challenge/blob/f0b7ae84781042b5ff1ead8290cc5061c8905909/src/components/Input.js#L14-L15

Reemplazar los valores numericos mayores a 1 con responsive size y si es el fontSize con normalize, estan en el boilerplaite en src>utils>dimentions

**Comment by LcsGrz** [comment]
Este proyecto no trae RS y normalize @IanCiarulli

**Comment by IanCiarulli** [comment]
Por eso le dije que en el boiler estaban, @LcsGrz , solo que no se si Javi les habra dado acceso al boiler para que lo usen de guia.

**Comment by FranFara** [comment]
Se agrego RS y normalize.
